apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pepa.fullname" . }}-secrets
  labels:
    {{- include "pepa.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  AUTH_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.postgresPassword }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
