apiVersion: v2
name: pepa
description: PEPA — Platform Engineering & Pipeline Automator
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - platform-engineering
  - internal-developer-portal
  - idp
  - gitops
  - cncf
  - developer-tools
home: https://github.com/AlexsandrKotov/pepa
sources:
  - https://github.com/AlexsandrKotov/pepa
maintainers:
  - name: PEPA Maintainers
    email: maintainers@pepa.io
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: developer-tools
dependencies:
  - name: postgresql
    version: "~15"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~19"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
