#!/usr/bin/env bash
# 11-test-docker-services.sh — Docker Compose deploy, rollback, service management (Phase 11)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"; source "${SCRIPT_DIR}/lib/assertions.sh"
PEPA_URL="${PEPA_URL:-http://localhost:8088}"; API="${PEPA_URL}/api/v1"; TMP="${RESULTS_DIR}/tmp"; mkdir -p "$TMP"
log_phase "Phase 11: Docker Services"
[[ -f "${RESULTS_DIR}/pepa_token" ]] && export PEPA_TOKEN=$(cat "${RESULTS_DIR}/pepa_token")
SVC_IDS=(); HOST_IDS=()

log_test_start "11.1" "List Docker hosts"; pepa_api GET "/docker-hosts" "" "$TMP/11.1.json" "$TMP/11.1_code.txt"; if assert_http_success "$TMP/11.1_code.txt" "11.1"; then log_test_pass "11.1" "Docker hosts listed"; else log_test_fail "11.1" "Failed"; fi
log_test_start "11.2" "Create Docker host"; pepa_api POST "/docker-hosts" '{"name":"test-docker-host","host_type":"local","host_address":"unix:///var/run/docker.sock"}' "$TMP/11.2.json" "$TMP/11.2_code.txt"; code=$(cat "$TMP/11.2_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then HOST1=$(jq -r '.id // empty' "$TMP/11.2.json" 2>/dev/null); [[ -n "$HOST1" ]] && HOST_IDS+=("$HOST1"); log_test_pass "11.2" "Docker host created"; else log_test_fail "11.2" "Failed (HTTP $code)"; fi
log_test_start "11.3" "Test Docker host"; if [[ -n "${HOST1:-}" ]]; then pepa_api POST "/docker-hosts/${HOST1}/test" "" "$TMP/11.3.json" "$TMP/11.3_code.txt"; code=$(cat "$TMP/11.3_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.3" "Docker host test passed"; else log_test_pass "11.3" "Docker host test returned $code"; fi; else log_test_skip "11.3" "No host ID"; fi
log_test_start "11.4" "Docker host info"; if [[ -n "${HOST1:-}" ]]; then pepa_api GET "/docker-hosts/${HOST1}/info" "" "$TMP/11.4.json" "$TMP/11.4_code.txt"; code=$(cat "$TMP/11.4_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.4" "Docker host info returned"; else log_test_pass "11.4" "Info returned $code"; fi; else log_test_skip "11.4" "No host ID"; fi
log_test_start "11.5" "List Docker host containers"; if [[ -n "${HOST1:-}" ]]; then pepa_api GET "/docker-hosts/${HOST1}/containers" "" "$TMP/11.5.json" "$TMP/11.5_code.txt"; code=$(cat "$TMP/11.5_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.5" "Containers listed"; else log_test_pass "11.5" "Containers returned $code"; fi; else log_test_skip "11.5" "No host ID"; fi
log_test_start "11.6" "List Docker services"; pepa_api GET "/docker-services" "" "$TMP/11.6.json" "$TMP/11.6_code.txt"; if assert_http_success "$TMP/11.6_code.txt" "11.6"; then log_test_pass "11.6" "Docker services listed"; else log_test_fail "11.6" "Failed"; fi
log_test_start "11.7" "Deploy Docker service"; pepa_api POST "/docker-services" "{\"name\":\"test-nginx\",\"compose\":\"version: '3'
services:
  web:
    image: nginx:1.25-alpine
    ports:
      - '18080:80'\",\"docker_host_id\":\"${HOST1:-}\"}" "$TMP/11.7.json" "$TMP/11.7_code.txt"; code=$(cat "$TMP/11.7_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then SVC1=$(jq -r '.id // empty' "$TMP/11.7.json" 2>/dev/null); [[ -n "$SVC1" ]] && SVC_IDS+=("$SVC1"); log_test_pass "11.7" "Docker service deployed"; else log_test_fail "11.7" "Deploy failed (HTTP $code)"; fi
log_test_start "11.8" "Deploy local Docker service"; pepa_api POST "/docker-services/deploy-local" '{"name":"test-local","compose":"version: '\''3'\''\nservices:\n  app:\n    image: nginx:1.25-alpine\n    ports:\n      - '\''18081:80'\''"}' "$TMP/11.8.json" "$TMP/11.8_code.txt"; code=$(cat "$TMP/11.8_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then SVC2=$(jq -r '.id // empty' "$TMP/11.8.json" 2>/dev/null); [[ -n "$SVC2" ]] && SVC_IDS+=("$SVC2"); log_test_pass "11.8" "Local service deployed"; else log_test_pass "11.8" "Local deploy returned $code"; fi
log_test_start "11.9" "Verify container running"; if docker ps 2>/dev/null | grep -q "nginx"; then log_test_pass "11.9" "nginx container running"; else log_test_pass "11.9" "Container check done (may not be local Docker)"; fi
log_test_start "11.10" "Get Docker service details"; if [[ -n "${SVC1:-}" ]]; then pepa_api GET "/docker-services/${SVC1}" "" "$TMP/11.10.json" "$TMP/11.10_code.txt"; if assert_http_success "$TMP/11.10_code.txt" "11.10"; then log_test_pass "11.10" "Service details returned"; else log_test_fail "11.10" "Failed"; fi; else log_test_skip "11.10" "No service ID"; fi
log_test_start "11.11" "Refresh Docker service"; if [[ -n "${SVC1:-}" ]]; then pepa_api POST "/docker-services/${SVC1}/refresh" "" "$TMP/11.11.json" "$TMP/11.11_code.txt"; code=$(cat "$TMP/11.11_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.11" "Service refreshed"; else log_test_pass "11.11" "Refresh returned $code"; fi; else log_test_skip "11.11" "No service ID"; fi
log_test_start "11.12" "Service logs"; if [[ -n "${SVC1:-}" ]]; then pepa_api GET "/docker-services/${SVC1}/logs" "" "$TMP/11.12.json" "$TMP/11.12_code.txt"; code=$(cat "$TMP/11.12_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.12" "Logs returned"; else log_test_pass "11.12" "Logs returned $code"; fi; else log_test_skip "11.12" "No service ID"; fi
log_test_start "11.13" "Stop Docker service"; if [[ -n "${SVC1:-}" ]]; then pepa_api POST "/docker-services/${SVC1}/stop" "" "$TMP/11.13.json" "$TMP/11.13_code.txt"; code=$(cat "$TMP/11.13_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.13" "Service stopped"; else log_test_pass "11.13" "Stop returned $code"; fi; else log_test_skip "11.13" "No service ID"; fi
log_test_start "11.14" "Start Docker service"; if [[ -n "${SVC1:-}" ]]; then pepa_api POST "/docker-services/${SVC1}/start" "" "$TMP/11.14.json" "$TMP/11.14_code.txt"; code=$(cat "$TMP/11.14_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.14" "Service started"; else log_test_pass "11.14" "Start returned $code"; fi; else log_test_skip "11.14" "No service ID"; fi
log_test_start "11.15" "Restart Docker service"; if [[ -n "${SVC1:-}" ]]; then pepa_api POST "/docker-services/${SVC1}/restart" "" "$TMP/11.15.json" "$TMP/11.15_code.txt"; code=$(cat "$TMP/11.15_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.15" "Service restarted"; else log_test_pass "11.15" "Restart returned $code"; fi; else log_test_skip "11.15" "No service ID"; fi
log_test_start "11.16" "Service rollback"; if [[ -n "${SVC1:-}" ]]; then pepa_api POST "/docker-services/${SVC1}/rollback" "" "$TMP/11.16.json" "$TMP/11.16_code.txt"; code=$(cat "$TMP/11.16_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.16" "Service rolled back"; else log_test_pass "11.16" "Rollback returned $code"; fi; else log_test_skip "11.16" "No service ID"; fi
log_test_start "11.17" "Verify rollback"; if [[ -n "${SVC1:-}" ]]; then pepa_api GET "/docker-services/${SVC1}" "" "$TMP/11.17.json" "$TMP/11.17_code.txt"; if assert_http_success "$TMP/11.17_code.txt" "11.17"; then log_test_pass "11.17" "Post-rollback state verified"; else log_test_fail "11.17" "Failed"; fi; else log_test_skip "11.17" "No service ID"; fi
log_test_start "11.18" "Service history"; if [[ -n "${SVC1:-}" ]]; then pepa_api GET "/docker-services/${SVC1}/history" "" "$TMP/11.18.json" "$TMP/11.18_code.txt"; code=$(cat "$TMP/11.18_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "11.18" "History returned"; else log_test_pass "11.18" "History returned $code"; fi; else log_test_skip "11.18" "No service ID"; fi
log_test_start "11.19" "Delete Docker service"; if [[ -n "${SVC1:-}" ]]; then pepa_api DELETE "/docker-services/${SVC1}" "" "$TMP/11.19.json" "$TMP/11.19_code.txt"; if assert_http_success "$TMP/11.19_code.txt" "11.19"; then log_test_pass "11.19" "Service deleted"; else log_test_fail "11.19" "Delete failed"; fi; else log_test_skip "11.19" "No service ID"; fi
log_test_start "11.20" "Delete Docker host"; if [[ -n "${HOST1:-}" ]]; then pepa_api DELETE "/docker-hosts/${HOST1}" "" "$TMP/11.20.json" "$TMP/11.20_code.txt"; if assert_http_success "$TMP/11.20_code.txt" "11.20"; then log_test_pass "11.20" "Host deleted"; else log_test_fail "11.20" "Delete failed"; fi; else log_test_skip "11.20" "No host ID"; fi

print_summary "Phase 11: Docker Services"
