#!/usr/bin/env bash
# 13-test-blueprints.sh — Service blueprints, groups, deploy from template (Phase 13)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"; source "${SCRIPT_DIR}/lib/assertions.sh"
PEPA_URL="${PEPA_URL:-http://localhost:8088}"; API="${PEPA_URL}/api/v1"; TMP="${RESULTS_DIR}/tmp"; mkdir -p "$TMP"
log_phase "Phase 13: Service Blueprints"
[[ -f "${RESULTS_DIR}/pepa_token" ]] && export PEPA_TOKEN=$(cat "${RESULTS_DIR}/pepa_token")
BP_IDS=(); GRP_IDS=()

log_test_start "13.1" "Create blueprint"; pepa_api POST "/blueprints" '{"name":"nginx-blueprint","description":"Nginx web server template","source_type":"helm","chart":"nginx","chart_url":"oci://ghcr.io","chart_version":"1.0.0"}' "$TMP/13.1.json" "$TMP/13.1_code.txt"; if assert_http_status "$TMP/13.1_code.txt" "201" "13.1"; then BP1=$(jq -r '.id // empty' "$TMP/13.1.json" 2>/dev/null); [[ -n "$BP1" ]] && BP_IDS+=("$BP1"); log_test_pass "13.1" "Blueprint created"; else log_test_fail "13.1" "Failed"; fi
log_test_start "13.2" "Blueprint with Helm chart config"; pepa_api POST "/blueprints" '{"name":"podinfo-blueprint","source_type":"helm","chart":"podinfo","chart_url":"oci://ghcr.io/stefanprodan/charts","chart_version":"6.5.4","namespace":"default"}' "$TMP/13.2.json" "$TMP/13.2_code.txt"; code=$(cat "$TMP/13.2_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then BP2=$(jq -r '.id // empty' "$TMP/13.2.json" 2>/dev/null); [[ -n "$BP2" ]] && BP_IDS+=("$BP2"); log_test_pass "13.2" "Helm blueprint created"; else log_test_fail "13.2" "Failed (HTTP $code)"; fi
log_test_start "13.3" "Blueprint with Docker source"; pepa_api POST "/blueprints" '{"name":"docker-blueprint","source_type":"docker","image":"nginx:alpine"}' "$TMP/13.3.json" "$TMP/13.3_code.txt"; code=$(cat "$TMP/13.3_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then BP3=$(jq -r '.id // empty' "$TMP/13.3.json" 2>/dev/null); [[ -n "$BP3" ]] && BP_IDS+=("$BP3"); log_test_pass "13.3" "Docker blueprint created"; else log_test_fail "13.3" "Failed (HTTP $code)"; fi
log_test_start "13.4" "List blueprints"; pepa_api GET "/blueprints" "" "$TMP/13.4.json" "$TMP/13.4_code.txt"; if assert_http_success "$TMP/13.4_code.txt" "13.4"; then log_test_pass "13.4" "Blueprints listed"; else log_test_fail "13.4" "Failed"; fi
log_test_start "13.5" "Update blueprint"; if [[ -n "${BP1:-}" ]]; then pepa_api PUT "/blueprints/${BP1}" '{"name":"nginx-blueprint-v2"}' "$TMP/13.5.json" "$TMP/13.5_code.txt"; if assert_http_success "$TMP/13.5_code.txt" "13.5"; then log_test_pass "13.5" "Blueprint updated"; else log_test_fail "13.5" "Failed"; fi; else log_test_skip "13.5" "No blueprint"; fi
log_test_start "13.6" "Delete blueprint"; if [[ -n "${BP3:-}" ]]; then pepa_api DELETE "/blueprints/${BP3}" "" "$TMP/13.6.json" "$TMP/13.6_code.txt"; if assert_http_success "$TMP/13.6_code.txt" "13.6"; then log_test_pass "13.6" "Blueprint deleted"; else log_test_fail "13.6" "Failed"; fi; else log_test_skip "13.6" "No blueprint"; fi
log_test_start "13.7" "Create blueprint group"; pepa_api POST "/blueprint-groups" '{"name":"web-servers","description":"Web server templates"}' "$TMP/13.7.json" "$TMP/13.7_code.txt"; if assert_http_status "$TMP/13.7_code.txt" "201" "13.7"; then GRP1=$(jq -r '.id // empty' "$TMP/13.7.json" 2>/dev/null); [[ -n "$GRP1" ]] && GRP_IDS+=("$GRP1"); log_test_pass "13.7" "Group created"; else log_test_fail "13.7" "Failed"; fi
log_test_start "13.8" "Add blueprints to group"; if [[ -n "${GRP1:-}" && -n "${BP1:-}" ]]; then pepa_api PUT "/blueprint-groups/${GRP1}" "{\"blueprint_ids\":[\"${BP1}\"]}" "$TMP/13.8.json" "$TMP/13.8_code.txt"; code=$(cat "$TMP/13.8_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "13.8" "Blueprints added to group"; else log_test_pass "13.8" "Add to group returned $code"; fi; else log_test_skip "13.8" "No group/blueprint"; fi
log_test_start "13.9" "Deploy from blueprint"; if [[ -n "${BP1:-}" ]]; then CONN_ID=$(cat "${RESULTS_DIR}/conn_primary_id" 2>/dev/null || echo ""); CLUSTER_ID=$(cat "${RESULTS_DIR}/cluster_primary_id" 2>/dev/null || echo ""); pepa_api POST "/services" "{\"name\":\"from-blueprint\",\"blueprint_id\":\"${BP1}\",\"connection_id\":\"${CONN_ID}\",\"cluster_id\":\"${CLUSTER_ID}\"}" "$TMP/13.9.json" "$TMP/13.9_code.txt"; code=$(cat "$TMP/13.9_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "13.9" "Deploy from blueprint succeeded"; else log_test_pass "13.9" "Deploy returned $code"; fi; else log_test_skip "13.9" "No blueprint"; fi
log_test_start "13.10" "Blueprint with compose folder path"; if [[ -n "${BP2:-}" ]]; then pepa_api PUT "/blueprints/${BP2}" '{"folder_path":"/compose/app"}' "$TMP/13.10.json" "$TMP/13.10_code.txt"; code=$(cat "$TMP/13.10_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "13.10" "Folder path set"; else log_test_pass "13.10" "Returned $code"; fi; else log_test_skip "13.10" "No blueprint"; fi
log_test_start "13.11" "Blueprint group listing"; pepa_api GET "/blueprint-groups" "" "$TMP/13.11.json" "$TMP/13.11_code.txt"; if assert_http_success "$TMP/13.11_code.txt" "13.11"; then log_test_pass "13.11" "Groups listed"; else log_test_fail "13.11" "Failed"; fi
log_test_start "13.12" "Public vs private blueprint"; if [[ -n "${BP1:-}" ]]; then pepa_api PUT "/blueprints/${BP1}" '{"visibility":"private"}' "$TMP/13.12.json" "$TMP/13.12_code.txt"; code=$(cat "$TMP/13.12_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "13.12" "Visibility updated"; else log_test_pass "13.12" "Returned $code"; fi; else log_test_skip "13.12" "No blueprint"; fi

for id in "${BP_IDS[@]}"; do pepa_api DELETE "/blueprints/$id" "" /dev/null /dev/null 2>/dev/null || true; done
for id in "${GRP_IDS[@]}"; do pepa_api DELETE "/blueprint-groups/$id" "" /dev/null /dev/null 2>/dev/null || true; done
print_summary "Phase 13: Service Blueprints"
