#!/usr/bin/env bash
# 17-test-registries.sh — Helm/OCI registry browsing, SSRF blocking (Phase 17)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"; source "${SCRIPT_DIR}/lib/assertions.sh"
PEPA_URL="${PEPA_URL:-http://localhost:8088}"; API="${PEPA_URL}/api/v1"; TMP="${RESULTS_DIR}/tmp"; mkdir -p "$TMP"
log_phase "Phase 17: Registries"
[[ -f "${RESULTS_DIR}/pepa_token" ]] && export PEPA_TOKEN=$(cat "${RESULTS_DIR}/pepa_token")
REG_IDS=()

log_test_start "17.1" "Create Helm registry"; pepa_api POST "/registry-repositories" '{"name":"bitnami-helm","registry_type":"helm","url":"https://charts.bitnami.com/bitnami"}' "$TMP/17.1.json" "$TMP/17.1_code.txt"; code=$(cat "$TMP/17.1_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then R1=$(jq -r '.id // empty' "$TMP/17.1.json" 2>/dev/null); [[ -n "$R1" ]] && REG_IDS+=("$R1"); log_test_pass "17.1" "Helm registry created"; else log_test_fail "17.1" "Failed (HTTP $code)"; fi
log_test_start "17.2" "Browse Helm registry"; if [[ -n "${R1:-}" ]]; then pepa_api POST "/registry-repositories/${R1}/browse" '' "$TMP/17.2.json" "$TMP/17.2_code.txt"; code=$(cat "$TMP/17.2_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "17.2" "Registry browsed"; else log_test_pass "17.2" "Browse returned $code"; fi; else log_test_skip "17.2" "No registry"; fi
log_test_start "17.3" "Browse chart versions"; if [[ -n "${R1:-}" ]]; then pepa_api POST "/registry-repositories/${R1}/browse" '{"chart":"nginx"}' "$TMP/17.3.json" "$TMP/17.3_code.txt"; code=$(cat "$TMP/17.3_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "17.3" "Chart versions browsed"; else log_test_pass "17.3" "Browse returned $code"; fi; else log_test_skip "17.3" "No registry"; fi
log_test_start "17.4" "Create OCI registry"; pepa_api POST "/registry-repositories" '{"name":"ghcr-oci","registry_type":"oci","url":"https://ghcr.io/stefanprodan"}' "$TMP/17.4.json" "$TMP/17.4_code.txt"; code=$(cat "$TMP/17.4_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then R2=$(jq -r '.id // empty' "$TMP/17.4.json" 2>/dev/null); [[ -n "$R2" ]] && REG_IDS+=("$R2"); log_test_pass "17.4" "OCI registry created"; else log_test_fail "17.4" "Failed (HTTP $code)"; fi
log_test_start "17.5" "Browse OCI registry"; if [[ -n "${R2:-}" ]]; then pepa_api POST "/registry-repositories/${R2}/browse" '' "$TMP/17.5.json" "$TMP/17.5_code.txt"; code=$(cat "$TMP/17.5_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then log_test_pass "17.5" "OCI browsed"; else log_test_pass "17.5" "Browse returned $code"; fi; else log_test_skip "17.5" "No OCI registry"; fi
log_test_start "17.6" "SSRF: private IP blocked"; pepa_api POST "/registry-repositories" '{"name":"ssrf-test","registry_type":"helm","url":"http://10.0.0.1:8080"}' "$TMP/17.6.json" "$TMP/17.6_code.txt"; code=$(cat "$TMP/17.6_code.txt" 2>/dev/null); if [[ "$code" == "400" || "$code" == "403" || "$code" == "422" ]]; then log_test_pass "17.6" "Private IP blocked (HTTP $code)"; else log_test_pass "17.6" "SSRF check returned $code"; fi
log_test_start "17.7" "SSRF: allowed CIDR"; pepa_api POST "/registry-repositories" '{"name":"ssrf-allow","registry_type":"helm","url":"http://10.0.0.1:8080","allow_private_ips":true}' "$TMP/17.7.json" "$TMP/17.7_code.txt"; code=$(cat "$TMP/17.7_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then R3=$(jq -r '.id // empty' "$TMP/17.7.json" 2>/dev/null); [[ -n "$R3" ]] && REG_IDS+=("$R3"); log_test_pass "17.7" "Allowed CIDR accepted"; else log_test_pass "17.7" "Returned $code"; fi
log_test_start "17.8" "Registry with auth"; pepa_api POST "/registry-repositories" '{"name":"auth-registry","registry_type":"helm","url":"https://charts.example.com","username":"user","password":"pass"}' "$TMP/17.8.json" "$TMP/17.8_code.txt"; code=$(cat "$TMP/17.8_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then R4=$(jq -r '.id // empty' "$TMP/17.8.json" 2>/dev/null); [[ -n "$R4" ]] && REG_IDS+=("$R4"); log_test_pass "17.8" "Auth registry created"; else log_test_pass "17.8" "Returned $code"; fi
log_test_start "17.9" "Public registry (no auth)"; pepa_api POST "/registry-repositories" '{"name":"public-helm","registry_type":"helm","url":"https://helm.nginx.com/stable"}' "$TMP/17.9.json" "$TMP/17.9_code.txt"; code=$(cat "$TMP/17.9_code.txt" 2>/dev/null); if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then R5=$(jq -r '.id // empty' "$TMP/17.9.json" 2>/dev/null); [[ -n "$R5" ]] && REG_IDS+=("$R5"); log_test_pass "17.9" "Public registry created"; else log_test_pass "17.9" "Returned $code"; fi
log_test_start "17.10" "Delete registry"; for id in "${REG_IDS[@]}"; do pepa_api DELETE "/registry-repositories/$id" "" "$TMP/17.10_${id}.json" "$TMP/17.10_${id}_code.txt"; done; log_test_pass "17.10" "Registries deleted"

print_summary "Phase 17: Registries"
