// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/plugin/proto/plugin.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PluginType    string                 `protobuf:"bytes,4,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"` // git_provider, task_tracker, cd_engine, etc.
	Actions       []*ActionInfo          `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *InfoResponse) GetActions() []*ActionInfo {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *InfoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ActionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   string                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionInfo) Reset() {
	*x = ActionInfo{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInfo) ProtoMessage() {}

func (x *ActionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInfo.ProtoReflect.Descriptor instead.
func (*ActionInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ActionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionInfo) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

type ExecuteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Action           string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params           []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // JSON-encoded parameters
	TenantId         string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ConnectionConfig map[string]string      `protobuf:"bytes,4,rep,name=connection_config,json=connectionConfig,proto3" json:"connection_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // connection credentials/settings
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecuteRequest) GetConnectionConfig() map[string]string {
	if x != nil {
		return x.ConnectionConfig
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // JSON-encoded result
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_internal_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\"internal/plugin/proto/plugin.proto\x12\x06plugin\"\r\n" +
	"\vInfoRequest\"\xaa\x02\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vplugin_type\x18\x04 \x01(\tR\n" +
	"pluginType\x12,\n" +
	"\aactions\x18\x05 \x03(\v2\x12.plugin.ActionInfoR\aactions\x12>\n" +
	"\bmetadata\x18\x06 \x03(\v2\".plugin.InfoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\n" +
	"ActionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema\"\xfd\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12Y\n" +
	"\x11connection_config\x18\x04 \x03(\v2,.plugin.ExecuteRequest.ConnectionConfigEntryR\x10connectionConfig\x1aC\n" +
	"\x15ConnectionConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"f\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs2\xc3\x01\n" +
	"\n" +
	"PEPAPlugin\x121\n" +
	"\x04Info\x12\x13.plugin.InfoRequest\x1a\x14.plugin.InfoResponse\x12:\n" +
	"\aExecute\x12\x16.plugin.ExecuteRequest\x1a\x17.plugin.ExecuteResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.plugin.HealthCheckRequest\x1a\x1b.plugin.HealthCheckResponseB,Z*github.com/pepa/pepa/internal/plugin/protob\x06proto3"

var (
	file_internal_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_plugin_proto_rawDescData []byte
)

func file_internal_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_internal_plugin_proto_plugin_proto_rawDescData
}

var file_internal_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_plugin_proto_plugin_proto_goTypes = []any{
	(*InfoRequest)(nil),         // 0: plugin.InfoRequest
	(*InfoResponse)(nil),        // 1: plugin.InfoResponse
	(*ActionInfo)(nil),          // 2: plugin.ActionInfo
	(*ExecuteRequest)(nil),      // 3: plugin.ExecuteRequest
	(*ExecuteResponse)(nil),     // 4: plugin.ExecuteResponse
	(*HealthCheckRequest)(nil),  // 5: plugin.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 6: plugin.HealthCheckResponse
	nil,                         // 7: plugin.InfoResponse.MetadataEntry
	nil,                         // 8: plugin.ExecuteRequest.ConnectionConfigEntry
}
var file_internal_plugin_proto_plugin_proto_depIdxs = []int32{
	2, // 0: plugin.InfoResponse.actions:type_name -> plugin.ActionInfo
	7, // 1: plugin.InfoResponse.metadata:type_name -> plugin.InfoResponse.MetadataEntry
	8, // 2: plugin.ExecuteRequest.connection_config:type_name -> plugin.ExecuteRequest.ConnectionConfigEntry
	0, // 3: plugin.PEPAPlugin.Info:input_type -> plugin.InfoRequest
	3, // 4: plugin.PEPAPlugin.Execute:input_type -> plugin.ExecuteRequest
	5, // 5: plugin.PEPAPlugin.HealthCheck:input_type -> plugin.HealthCheckRequest
	1, // 6: plugin.PEPAPlugin.Info:output_type -> plugin.InfoResponse
	4, // 7: plugin.PEPAPlugin.Execute:output_type -> plugin.ExecuteResponse
	6, // 8: plugin.PEPAPlugin.HealthCheck:output_type -> plugin.HealthCheckResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_plugin_proto_init() }
func file_internal_plugin_proto_plugin_proto_init() {
	if File_internal_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_plugin_proto = out.File
	file_internal_plugin_proto_plugin_proto_goTypes = nil
	file_internal_plugin_proto_plugin_proto_depIdxs = nil
}
