// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PEPAPlugin_Info_FullMethodName        = "/plugin.PEPAPlugin/Info"
	PEPAPlugin_Execute_FullMethodName     = "/plugin.PEPAPlugin/Execute"
	PEPAPlugin_HealthCheck_FullMethodName = "/plugin.PEPAPlugin/HealthCheck"
)

// PEPAPluginClient is the client API for PEPAPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PEPAPlugin is the gRPC service that ALL PEPA plugins must implement.
type PEPAPluginClient interface {
	// Info returns metadata about the plugin.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Execute runs a named action with JSON parameters.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// HealthCheck returns the current health status.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pEPAPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPEPAPluginClient(cc grpc.ClientConnInterface) PEPAPluginClient {
	return &pEPAPluginClient{cc}
}

func (c *pEPAPluginClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, PEPAPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pEPAPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, PEPAPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pEPAPluginClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PEPAPlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PEPAPluginServer is the server API for PEPAPlugin service.
// All implementations must embed UnimplementedPEPAPluginServer
// for forward compatibility.
//
// PEPAPlugin is the gRPC service that ALL PEPA plugins must implement.
type PEPAPluginServer interface {
	// Info returns metadata about the plugin.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Execute runs a named action with JSON parameters.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// HealthCheck returns the current health status.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPEPAPluginServer()
}

// UnimplementedPEPAPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPEPAPluginServer struct{}

func (UnimplementedPEPAPluginServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPEPAPluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedPEPAPluginServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPEPAPluginServer) mustEmbedUnimplementedPEPAPluginServer() {}
func (UnimplementedPEPAPluginServer) testEmbeddedByValue()                    {}

// UnsafePEPAPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PEPAPluginServer will
// result in compilation errors.
type UnsafePEPAPluginServer interface {
	mustEmbedUnimplementedPEPAPluginServer()
}

func RegisterPEPAPluginServer(s grpc.ServiceRegistrar, srv PEPAPluginServer) {
	// If the following call panics, it indicates UnimplementedPEPAPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PEPAPlugin_ServiceDesc, srv)
}

func _PEPAPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PEPAPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PEPAPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PEPAPluginServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PEPAPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PEPAPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PEPAPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PEPAPluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PEPAPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PEPAPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PEPAPlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PEPAPluginServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PEPAPlugin_ServiceDesc is the grpc.ServiceDesc for PEPAPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PEPAPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PEPAPlugin",
	HandlerType: (*PEPAPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _PEPAPlugin_Info_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _PEPAPlugin_Execute_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PEPAPlugin_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugin/proto/plugin.proto",
}
